[package]
name = "rustypass"
version = "0.1.0"
authors = ["Juha Ruotsalainen <juha.ruotsalainen@iki.fi>"]
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.64"
publish = false


[dependencies]
eframe = "0.19.0"
egui_extras = "0.19.0"
walkdir = "2.3.2"
